#! /usr/bin/env bash

echo "===Delete Object==="

if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 --bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > s3/bash-scripts/object_list.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file://s3/bash-scripts/object_list.json

