#! /usr/bin/env bash
echo "====Delete Bucket==="
#check if argument is provided

if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

BUCKET_NAME=$1
aws s3api delete-bucket --bucket $BUCKET_NAME